package com.example.travelapp.ui.viewmodels

import android.content.Context
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.travelapp.R
import com.example.travelapp.database.models.ItineraryItem
import com.example.travelapp.database.repositories.ItineraryRepository
import com.google.ai.client.generativeai.GenerativeModel
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.time.LocalDate
import javax.inject.Inject

data class AiItineraryItem(
    val title: String,
    val description: String,
    val isSelected: Boolean = false
)

data class AiItineraryUiState(
    val isLoading: Boolean = false,
    val suggestions: List<AiItineraryItem> = emptyList(),
    val selectedDate: LocalDate? = null,
    val errorMessage: String? = null,
    val addedSuccessfully: Boolean = false
)

/**
 * ViewModel responsible for managing itinerary items generated by AI for a specific trip.
 *
 * Handles generating itinerary suggestions and adding them to the user's itinerary.
 *
 * Coordinates with [ItineraryRepository] for data persistence.
 * Uses [GenerativeModel] for AI generation
 */
@HiltViewModel
class AiItineraryViewModel @Inject constructor(
    private val generativeModel: GenerativeModel,
    private val itineraryRepository: ItineraryRepository,
    @param:ApplicationContext private val context: Context
) : ViewModel() {
    private val _uiState = MutableStateFlow(AiItineraryUiState())
    val uiState: StateFlow<AiItineraryUiState> = _uiState.asStateFlow()

    /**
     * Selects the date for which to generate the itinerary
     */
    fun onDateSelected(date: LocalDate) {
        _uiState.update {
            it.copy(
                selectedDate = date,
                suggestions = emptyList(),
                errorMessage = null
            )
        }
    }

    /**
     * Selects the itinerary item which is going to be added when pressing the Add selected button
     *
     * @param index Index of the item to add
     */
    fun toggleItemSelection(index: Int) {
        val updated = _uiState.value.suggestions.mapIndexed { i, item ->
            if (i == index) item.copy(isSelected = !item.isSelected) else item
        }
        _uiState.update { it.copy(suggestions = updated) }
    }

    /**
     * Generates the itinerary for a specific trip
     *
     * @param tripLocation Trip Location for which to generate itinerary
     */
    fun generateItinerary(tripLocation: String) = viewModelScope.launch {
        val date = _uiState.value.selectedDate ?: return@launch

        _uiState.update { it.copy(isLoading = true, errorMessage = null) }

        try {
            val prompt = """
                Generate a detailed day itinerary for a tourist visiting $tripLocation on ${date}.
                
                Suggest 5 activities/places to visit throughout the day.
                For each activity provide:
                1. Short title (max 5 words)
                2. Brief description (1-2 sentences)
                
                Format your response EXACTLY like this:
                TITLE: [title]
                DESCRIPTION: [description]
                ---
                (repeat for each activity)
            """.trimIndent()

            val response = generativeModel.generateContent(prompt)
            val suggestions = parseResponse(response.text ?: "")

            _uiState.update { it.copy(isLoading = false, suggestions = suggestions) }
        }
        catch (e: Exception) {
            _uiState.update {
                it.copy(
                    isLoading = false,
                    errorMessage = context.getString(
                        R.string.failed_to_generate_itinerary,
                        e.message
                    )
                )
            }
        }
    }

    /**
     * Adds the selected items to the users itinerary for the provided trip.
     *
     * @param tripId ID of the trip for which to add the generated itinerary to the actual itinerary
     */
    fun addSelectedItems(tripId: Int) = viewModelScope.launch {
        val date = _uiState.value.selectedDate ?: return@launch
        val selectedItems = _uiState.value.suggestions.filter { it.isSelected }

        selectedItems.forEach { item ->
            itineraryRepository.addItem(
                ItineraryItem(
                    tripId = tripId,
                    date = date,
                    title = item.title,
                    description = item.description.ifBlank { null }
                )
            )
        }

        _uiState.update { it.copy(addedSuccessfully = true) }
    }

    /**
     * Resets the [uiState] by marking the addedSuccessfully flag to false
     */
    fun resetAddedSuccessfully() {
        _uiState.update { it.copy(addedSuccessfully = false) }
    }

    /**
     * Parses the generated AI response
     *
     * @param text Text to parse
     */
    private fun parseResponse(text: String): List<AiItineraryItem> {
        val items = mutableListOf<AiItineraryItem>()
        val blocks = text.split("---").filter { it.isNotBlank() }

        for (block in blocks) {
            val lines = block.lines().map { it.trim() }.filter { it.isNotEmpty() }
            var title = ""
            var description = ""

            for (line in lines) {
                when {
                    line.startsWith("TITLE:", ignoreCase = true) ->
                        title = line.substringAfter(":").trim()
                    line.startsWith("DESCRIPTION:", ignoreCase = true) ->
                        description = line.substringAfter(":").trim()
                }
            }

            if (title.isNotEmpty()) {
                items.add(AiItineraryItem(title, description))
            }
        }

        return items
    }
}